# Generated by Django 5.0.6 on 2024-06-20 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_user_referral_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TapAndEarn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('claimed_amount', models.IntegerField(blank=True)),
                ('time_last_claimed', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tap_and_earns', to='user.user')),
            ],
            options={
                'db_table': 'tap_and_earn',
            },
        ),
    ]
