# Generated by Django 5.0.6 on 2024-07-10 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_user_referral_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReward',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('daily_reward', models.IntegerField()),
                ('days_streak', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reward', to='user.user')),
            ],
            options={
                'db_table': 'daily_reward',
            },
        ),
    ]
