# Generated by Django 5.0.6 on 2024-06-05 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('head', models.CharField(default='default', max_length=255)),
                ('skin', models.CharField(default='default', max_length=255)),
                ('top', models.CharField(default='default', max_length=255)),
                ('bottom', models.CharField(default='default', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='agent.agent')),
            ],
            options={
                'db_table': 'avatars',
            },
        ),
    ]
