# Generated by Django 5.0.6 on 2024-07-10 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_referral_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_logged_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 5, 22, 25, 29, 466837), null=True),
        ),
    ]
