# Generated by Django 5.0.6 on 2024-07-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agent_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_chatting_with_user',
            field=models.BooleanField(default=False),
        ),
    ]
