# Generated by Django 5.0.6 on 2024-07-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agent_is_chatting_with_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='energy',
            field=models.IntegerField(blank=True, default=240),
        ),
        migrations.AddField(
            model_name='agent',
            name='luck',
            field=models.IntegerField(blank=True, default=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='mining_rate',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
