
name: CI/CD Workflow

on:
  push:
    branches:
    - dev
    - main

jobs:
  build_prod:
    runs-on: ubuntu-latest

    env:
      GA_ID: ${{ secrets.GA_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Cocos Creator
        run: |
          wget http://download.cocos.com/CocosCreator/v2.4.0/CocosCreator_v2.4.0_ubuntu_amd64.deb
          sudo dpkg -i CocosCreator_v2.4.0_ubuntu_amd64.deb
          sudo apt-get install -f

      - name: Build Cocos Creator project
        run: |
          /path/to/CocosCreator --path /path/to/your/project --build "platform=web-mobile;md5Cache=false;"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy to Amplify
        run: |
          npm install -g @aws-amplify/cli
          amplify status
          amplify push --yes

      - name: Notify on Discord
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            message="Build succeeded";
          else
            message="Build failed";
          fi
          curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"${message}\"}" ${{ secrets.DISCORD_WEBHOOK_URL }}

  build_stage:
    runs-on: ubuntu-latest

    env:
      GA_ID: ${{ secrets.GA_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

