name: CI/CD Workflow

on:
  push:
    branches:
    - dev
    - main

jobs:
  build_prod:
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'

    env:
      GA_ID: ${{ secrets.GA_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download and unzip Cocos Creator
        run: |
          curl -o CocosCreator.zip https://sanctum.s3.ap-southeast-1.amazonaws.com/CocosCreator.zip
          unzip -q CocosCreator.zip -d /Applications

      - name: Build Cocos Creator project
        run: |
          /Applications/CocosCreator.app/Contents/MacOS/CocosCreator --project ./Game --build "platform=web-mobile;buildPath=./Game/build;name=sanctum-telegram-game;platform=web-mobile;startScene=27507cdc-65b2-429e-8af5-395ac1f19b0e;replaceSplashScreen=true;debug=false"
        continue-on-error: true
    
      # aws credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      # - name: Setup Node.js environment
      #   uses: actions/setup-node@v4.0.3
          
      # - name: configure amplify
      #   uses: ambientlight/amplify-cli-action@0.3.0
      #   with:
      #     amplify_command: configure
      #     amplify_env: prod
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: us-east-1

      # - name: deploy
      #   uses: ambientlight/amplify-cli-action@0.3.0
      #   with:
      #     amplify_command: publish
      #     amplify_env: prod
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: us-east-1
          
      # discord
      - name: Notify on Discord
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            message="[sanctum-telegram-game] [build_prod] succeeded";
          else
            message="[sanctum-telegram-game] [build_prod] failed";
          fi
          curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"${message}\"}" ${{ secrets.DISCORD_WEBHOOK_URL }}
