
name: CI/CD Workflow

on:
  push:
    branches:
    - dev
    - main

jobs:
  build_prod:
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'

    env:
      GA_ID: ${{ secrets.GA_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download and unzip Cocos Creator
        run: |
          curl -o CocosCreator.zip https://sanctum.s3.ap-southeast-1.amazonaws.com/CocosCreator.zip
          unzip -q CocosCreator.zip -d /Applications
          ls /Applications/CocosCreator.app

      - name: Build Cocos Creator project
        run: |
          /Applications/CocosCreator.app/Contents/MacOS/CocosCreator --path ./Game/ --build "platform=web-mobile;startScene=roulette_page.scene"
    
      # aws credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
        
      # discord
      - name: Notify on Discord
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            message="[sanctum-telegram-game] [build_prod] succeeded";
          else
            message="[sanctum-telegram-game] [build_prod] failed";
          fi
          curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"${message}\"}" ${{ secrets.DISCORD_WEBHOOK_URL }}
